// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace STEM.Models
{
    public partial class School
    {
        public School()
        {
            User = new HashSet<User>();
        }

        public Guid SchoolId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }

        public virtual ICollection<User> User { get; set; }
    }
}