// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace STEM.Models
{
    public partial class UserSubject
    {
        public Guid UserSubjectId { get; set; }
        public Guid UserId { get; set; }
        public Guid SubjectId { get; set; }

        [JsonIgnore]
        public virtual Subjects Subject { get; set; }
        [JsonIgnore]
        public virtual User User { get; set; }
    }
}