// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace STEM.Models
{
    public partial class UserType
    {
        public UserType()
        {
            User = new HashSet<User>();
        }

        public Guid UserTypeId { get; set; }
        public string Type { get; set; }

        public virtual ICollection<User> User { get; set; }
    }
}