// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace STEM.Models
{
    public partial class User
    {
        public User()
        {
            UserSubject = new HashSet<UserSubject>();
        }

        public Guid UserId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int Grade { get; set; }
        public Guid? SchoolId { get; set; }
        public Guid? UserTypeId { get; set; }
        public string Password { get; set; }

        public virtual School School { get; set; }
        public virtual UserType UserType { get; set; }
        public virtual ICollection<UserSubject> UserSubject { get; set; }
    }
}